# Site settings
title: Siarhei's Blog
header-img: 'img/home-bg.jpg'
twitter_username: SvirskiSiarhei
github_username: happi-cat
linkedin_username: 263014095
vkontakte_username: meowter_kautsuo
# email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: /

# Build Settings
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
sass: 
  sass_dir: _sass
permalink: pretty
paginate: 5
exclude: ["package.json",".gitignore"]